### ISSUE TITLE
print.experiement method

### ISSUE THREAD

**Issue by meta00** [r-and-gama/rama#108]
This function print object experiment, like this

`exp0 <- experiment(
  data.frame(S0 = 999, I0 = 1, R0 = 0, beta = 1.5, gamma = .15),
  data.frame(S = 1, I = 1, R = 1),
  1000, 1, "sir", system.file("models", "sir.gaml", package = "rama"))
print(exp0)`

but when we take subset of the object like
`exp0[, 1]`

print function doesn't work very well.

**Comment by LucieContamin** [comment]
also the function `print.experiment` returns an error for the object in `example2.Rmd`

```
# load the experiment
exp <- load_experiment("prey_predator",
                       system.file("models", "NicolasPred.gaml",
                                   package = "rama"))
exp
Experiment with 1 simulation of 11 parameters and 4 observed variables
experiment name:  prey_predator 
input gaml file:  /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rama/models/NicolasPred.gaml 
model parameters:    p_Initial_number_of_preys_, p_Initial_number_of_predators_, p_Prey_Birth_Rate_, p_Predator_death_rate_, p_Predation_rate_, p_Predation_efficiency_, p_environment_size, p_danger_distance, p_happiness_distance, p_simulation_id, p_currentSeed 
observed variables:  r_mean_pop, r_micro_b, r_nb_predators, r_nb_preys 
Experiment overview:
Error in Math.data.frame(list(p_Initial_number_of_preys_ = 150L, p_Initial_number_of_predators_ = 50L,  : 
  non-numeric variable(s) in data frame: p_simulation_id
```

**Comment by meta00** [comment]
also the experiment object can have `BOOLEAN` as parameter types. Pls update the `print`function

**Comment by LucieContamin** [comment]
The function `print` does not take into account the column `output`, it might be interesting to add it also
