### ISSUE TITLE
load_experiment revised

### ISSUE THREAD

**Issue by meta00** [r-and-gama/rama#114]
@LucieContamin 

line 88-89 in `load_experiment.R` in branch `issue76`, can we change:

`variables <- make_df_dic(get_variables(out)[get_variables_names(model)])`
 `parameters <- make_df_dic(get_parameters(out)[get_parameters_names(model)])`

to 

`variables <- make_df_dic(get_variables(out))`
`parameters <- make_df_dic(get_parameters(out))`

then remove two functions `get_variables_names` and `get_parameters_names`

**Comment by LucieContamin** [comment]
I find an example when the : `make_df_dic(get_variables(out)[get_variables_names(model)])` is necessary. If you look at the behavior of `load_experiment()` with the experiment `run` in `snubbies.gaml`. For example:

```
> variables <- make_df_dic(get_variables(out)[get_variables_names(model)])
> variables
$out
  number_of_dispersers number_of_death
1                    1               1

$dic_g2r
  number_of_dispersers        number_of_death 
"number_of_dispersers"      "number_of_death" 
```
Whereas if we remove the `get_variables_names()` or the `get_parameters_names()`, we obtain:

```
> variables <- make_df_dic(get_variables(out))
> variables
$out
  number_of_dispersers number_of_death map
1                    1               1   1

$dic_g2r
  number_of_dispersers        number_of_death                    map 
"number_of_dispersers"      "number_of_death"                  "map" 

```
And the variable `map` is link to the display not the value in the experiment which will probably lead to some mistakes. 
So, I think it's better if we keep it as it is currently.

**Comment by LucieContamin** [comment]
Because of the display as the same behavior as variables, I agree to remove the functions `get_variables_names` and `get_parameters_names` and `get_all_names`
