### ISSUE TITLE
model loading failed

### ISSUE THREAD

**Issue by gnoubi** [r-and-gama/rama#117]
[rongeur1.0.zip](https://github.com/r-and-gama/rama/files/3028937/rongeur1.0.zip)
[rongeur1.0.zip](https://github.com/r-and-gama/rama/files/3028944/rongeur1.0.zip)

Hi, 

When I run this command : 
exp1 <- load_experiment("simulation", "/Users/nicolas/Documents/gama_rongeur/rongeur/rongeur1.0.gaml")

I got this error

Loading experiment "simulation" from file "rongeur1.0.gaml"...
Error in `[.data.frame`(get_variables(out), get_variables_names(model)) : 
  undefined columns selected
In addition: Warning message:
In readLines(file) :
  incomplete final line found on '/Users/nicolas/Documents/gama_rongeur/rongeur/rongeur1.0.gaml'

Do you have any idea about the reason ? 

cheers
Nicolas

**Comment by choisy** [comment]
Could you send us your `rongeur1.0.gaml` file please so that we can try ourselves?
Thanks, Marc.

**Comment by meta00** [comment]
@gnoubi the attached model rongeur.gaml doesn't run in Gama either. Can you send us a good one?

**Comment by meta00** [comment]
@gnoubi rongeur.gaml works now and thanks to that we could see how a model with "display" works. Thanks for the example. You can try the latest version.

**Comment by gnoubi** [comment]
See attached the last version of the model

Note that, since the last version of gama (last week version), NA value data are produced in xml file.

Nicolas

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by meta00** [comment]
No attachment?

**Comment by gnoubi** [comment]
There was an attachment

I try again with your mail. Do you receive ?

Nicolas

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by meta00** [comment]
Got it, thank you
