### ISSUE TITLE
Add note about validate gaml file before using rama

### ISSUE THREAD

**Issue by meta00** [r-and-gama/rama#119]
An erroneous gaml file can't be used in run_experiment, load_expriment, and the constructors. The current message is "Gama fails to read your experiment". To be more informative, shall we add a message, e.g. the gaml file needs validating in Gama before using rama, in the help of those functions and in the README?

**Comment by gnoubi** [comment]
The last version of Gama gives compilation errors and details. Perhaps, it could be used 

Nicolas 

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by meta00** [comment]
Did you mean version 1.8? 

For now, we get error numbers from gama headless, e.g. 13. Do you have a dictionary of error codes - details that we could use? Or another way of getting more error details from gama headless?
