### ISSUE TITLE
realexp function error

### ISSUE THREAD

**Issue by meta00** [r-and-gama/rama#127]
example `Toy Models/Epidemiology/models/SIR (ABM vs EBM).gaml`, might be related to non-filled display obsrates.

**Comment by LucieContamin** [comment]
Done in commit `b203e4c` in pull-request #123

**Comment by meta00** [comment]
running 
`
weather <- load_experiment("weather_coModeling", "/Users/haihb/Documents/Work/rama/ignored/gama_models/models/Toy Models/Comodels/PlantGrow and weather/weather.gaml")
run_experiment(weather, save=T)
`
give an error on `realexp`:
`
Error in matrix(vals, length(nfields), byrow = TRUE) : 
  'data' must be of a vector type, was 'NULL'
`
because the output file is empty

`
<?xml version="1.0" encoding="UTF-8"?>
<Simulation id="1" >
</Simulation>`

**Comment by LucieContamin** [comment]
Can you please send me the model in zip file, I cannot find it in my GAMA library?
