### ISSUE TITLE
Missing function in 2.3 (of the Using rama tutorial)

### ISSUE THREAD

**Issue by benoitgaudou** [r-and-gama/rama#13]
In the documentation, it is missing the R code in Section 2.3, 
[https://r-and-gama.github.io/rama/articles/using_rama.html#building-an-experiment-from-a-data-frame](https://r-and-gama.github.io/rama/articles/using_rama.html#building-an-experiment-from-a-data-frame)

after:
```
Let’s now transform this data frame into an experiment:
```

**Comment by choisy** [comment]
Yeah... The function is not ready yet, still under development ah ah ah!!!

**Comment by meta00** [comment]
Done

**Comment by benoitgaudou** [comment]
I reopen it, as even if the function has been implemented, the documentation has not been updated :-) 
https://r-and-gama.github.io/rama/articles/rama.html#building-an-experiment-from-a-data-frame

**Comment by choisy** [comment]
Correct and we are aware of this. The reason is that we are working on a polymorphic generic constructor and that not all methods have been written yet. Will be done very soon.
Thanks, Marc

**Comment by choisy** [comment]
See issue #19

**Comment by meta00** [comment]
@choisy can you update the tutorial https://r-and-gama.github.io/rama/articles/rama.html#building-an-experiment-from-a-data-frame pls?

**Comment by choisy** [comment]
Addressing by pull request #70
