### ISSUE TITLE
`setup_gama` should install gama 1.8 (official release)

### ISSUE THREAD

**Issue by LucieContamin** [r-and-gama/rama#144]
Currently, `setup_gama` downloads, install and configures GAMA version 1.8 RC2. Or this version does not work for `gaml` file with a display in `rama`  and we also have trouble to recuperate error message from the headless of this version. 

Is it possible to install the last version of GAMA 1.8 Official Release instead? This version works perfectly with our last version of `rama`.

**Comment by gnoubi** [comment]
Hi

Yes it possible ofcourse but the 1.8 gama release is not official. I can create an intermediate version.

Nico

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by LucieContamin** [comment]
OK, thank you very much.

**Comment by LucieContamin** [comment]
Done in commit `f61f4de` and `47142fb`
