### ISSUE TITLE
print.experiment error

### ISSUE THREAD

**Issue by meta00** [r-and-gama/rama#20]
Check this gaml, name of parameters contains space etc. by running

```r
out <- load_experiment("main", "Regression.gaml")
out
```
[Regression.gaml.zip](https://github.com/r-and-gama/rama/files/2664470/Regression.gaml.zip)

**Comment by choisy** [comment]
Can somebody provides the location of the GAML file in the GAMA file hierarchy please?

**Comment by choisy** [comment]
The example GAML file does not correspond to the example. Please send the good GAML file.

**Comment by choisy** [comment]
Regression.gaml seems to be a link, not a file.

**Comment by meta00** [comment]
good one uploaded

**Comment by LucieContamin** [comment]
Fixed in pull-request #15
