### ISSUE TITLE
Error in running experiment for exp2

### ISSUE THREAD

**Issue by jdzucker** [r-and-gama/rama#44]
> library(rama)
> output <- run_experiment(exp2)
Error in file(file, if (append) "a" else "w") : 
  cannot open the connection
In addition: Warning messages:
1: In dir.create(out_dir) :
  cannot create dir '/sir_1', reason 'Permission denied'
2: In file(file, if (append) "a" else "w") :
  cannot open file '/sir_1/sir.xml': No such file or directory
Called from: file(file, if (append) "a" else "w")
Browse[1]> Q

**Comment by LucieContamin** [comment]
It seems to be an `error` because of the missing attributes in the object. 
I will update the function `run_experiment` to test the presence of the attribute before running.
The function `experiment` should be updated to integrate the new attributes (`mkdir`, `dic`, ...).
