### ISSUE TITLE
Create a data frame for output values... 

### ISSUE THREAD

**Issue by jdzucker** [r-and-gama/rama#45]
Take into account the frequency

**Comment by choisy** [comment]
Can you please write more understandable comments so that anyone can understand the exact purpose of the issue? In what this issue is different from issue #43 ?

**Comment by choisy** [comment]
Also: before posting a new issue, please ensure that the topic you want to report has not been reported already by a previous issue (open or closed). For example, this issue does not seem much different from issue #43. If I'm right, please resolve this by keeping only one of these.

**Comment by jdzucker** [comment]
Close enough to #43. No need to keep this one open.
