### ISSUE TITLE
Documentation of get started : error on the use of experiment ( ... )

### ISSUE THREAD

**Issue by benoitgaudou** [r-and-gama/rama#57]
In the documentation "Get started", from section 1.1.2: 
https://r-and-gama.github.io/rama/articles/rama.html#building-an-experiment-from-scratch

The following line:
``` r
exp2 <- experiment(df, 
           parameters = c("S0", "I0", "R0", "beta", "gama"),
           obsrates = c("S", "I", "R"), tmax = "a", seed = "b",
           experiment = "sir", model = gaml_file)
````

returns the error:

```
Error in experiment(df, parameters = c("S0", "I0", "R0", "beta", "gama"),  : 
  unused argument (df)
```

as the experiment function does not seem to use a df as first parameter anymore.

And this mistake is also present in all the experiment function use.

**Comment by meta00** [comment]
If you pull from master and rebuild, it works? How did you install the package?

**Comment by benoitgaudou** [comment]
Hi,
I do not use the git version sorry.
I only use the version from R, following the tutorial:
```r
installed_packages <- row.names(installed.packages())
devtools::install_github("r-and-gama/rama")

library(rama)
setup_gama()
/Applications/Gama1.8_RC2_withJava.app

gaml_file <- system.file("examples", "sir.gaml", package = "rama")
exp1 <- load_experiment("sir", gaml_file, "sir")
exp1
class(exp1)

df <- data.frame("S0" = 999, "I0" = 1, "R0" = 0, "beta" = 1.5,
                 "gama" = 0.15, "S" = 1, "I" = 1, "R" = 1,
                 "a" = 1000, "b" = 1)

df


exp2 <- experiment(df, parameters = c("S0", "I0", "R0", "beta", "gama"),
                    obsrates = c("S", "I", "R"), tmax = "a", seed = "b",
                    experiment = "sir", model = gaml_file)
   ````

And I still have the error.

**Comment by jdzucker** [comment]
Salut Benoit
Sommes en voiture Lucie est étonnée car elle avait vérifié. On Check quand on arrive. Merci de la notification. ;-)
Jean-Daniel

**Comment by benoitgaudou** [comment]
My bad ... sorry... I forget to restart the session.
I seems to work now so I close it.
Thank you
Benoit
