### ISSUE TITLE
help.seach / ?? on rama

### ISSUE THREAD

**Issue by benoitgaudou** [r-and-gama/rama#58]
The function help.search("rama") or ??rama do not provide any results ("No results found").

It could be useful to get the list of all the possible functions of the package from this function, right?

**Comment by LucieContamin** [comment]
To have the list of all the possible function of the package, you can use the `Packages` tap in RStudio by clicking on the package name `rama`. 

I would say that the `help.search()` function is "for searching the help system for documentation matching a given character string in the (file) name, alias, title, concept or keyword entries (or any combination thereof)". It cannot be used to return a list of function possible, for example, it does not work either for printing all the function of other packages (`dplyr`, `base`, ...).  
But, it currently works for `rama` is it's intalled on your library. For example, to print all the function containing `gama` in `rama`: 
```
help.search("gama", package = "rama")
```
It will print a Help page with the link to multiple functions:
```
rama::call_gama |   | Run GAMA on a XML file
rama::defpath |   | Configure GAMA path and Java heap size
rama::is_gama_installed |   | Test if GAMA is intalled
rama::save_to_gama |   | Save an experiment plan to a GAMA XML file
rama::setup_gama |   | Download GAMA and configure
```

**Comment by choisy** [comment]
And if you simply type `help.search("gama")` it will return all the functions on your system that contain "gama" (case insensitive) in their definition, i.e. those from the `rama` package but not only. If you want to print at the command line all the objects (available to the user) of the `rama` package, type `ls("package:rama")`. Or you can do as Lucie explained at the beginning of her answer, which is the equivalent of the `help(package = rama)` command.
