### ISSUE TITLE
plot_params error message

### ISSUE THREAD

**Issue by benoitgaudou** [r-and-gama/rama#59]
By testing randomly the functions of the package, I notice that the `plot_params` returns an error on one-line experiments (or on experiments with no parameters with values that vary). As an example:
```r
df <- data.frame("S0" = 999, "I0" = 1, "R0" = 0, "beta" = 1.5,
                 "gama" = 0.15, "S" = 1, "I" = 1, "R" = 1,
                 "a" = 1000, "b" = 1)

exp2 <- experiment(df, parameters = c("S0", "I0", "R0", "beta", "gama"),
                   obsrates = c("S", "I", "R"), tmax = "a", seed = "b",
                   experiment = "sir", model = gaml_file)
exp2
plot_params(exp2)
```
I get the error:
```r
Error in stripchart.default(exp[, topidx[1]], xlab = colnames(exp)[topidx[1]]) : 
  invalid first argument
```

A second example is:
```r
exp1 <- load_experiment("sir", gaml_file, "sir")
exp5 <- repl(exp1, 10)
plot_params(exp5)
```

To improve the robustness of the function (even if I admit that they are border line cases), these cases could be taken into acount either un returning a meaning full error or by ploting a single point).

**Comment by jdzucker** [comment]
Je m’en occupe !
Jean-Daniel 

---------------------------------
Senior Researcher
Dir. of UMMISCO Lab IRD/Sorbonne University
Dir. of the International PhD Program Modeling Complex Systems SU/IRD
Head of ICAN INTEGROMICS

**Comment by choisy** [comment]
In English please :) (Thanh, for example, does not speak French).

**Comment by jdzucker** [comment]
The bug is corrected
