### ISSUE TITLE
On the reference documentation

### ISSUE THREAD

**Issue by benoitgaudou** [r-and-gama/rama#60]
I love the way the website of rama is made and its feature.
But hen was wandering in the reference page (https://r-and-gama.github.io/rama/reference/index.html), I admit I am a little bit lost in the organization of the functions. In particular, some sections seem to have duplicate elements (Manipulating experiment objects and Configuring the rama package seem to contain the same functions ?).
Another example, the section *Running experiments* seem to contain only 2 functions related to its title (call_gama, run_experiment) whereas the 2 other ones are less related.

**Comment by choisy** [comment]
That's right and this is actually due to a bug in the pkgdown package that generates the website. The bug has been reported to the authors. Will likely be fixed soon.

**Comment by choisy** [comment]
Has be fixed.
