### ISSUE TITLE
One question and two bugs in make_wkdir()

### ISSUE THREAD

**Issue by choisy** [r-and-gama/rama#67]
This issue contains 1 question and 2 bugs.

**Question**: It is unclear to me why the function `make_wkdir()` discriminates the cases where there is a `/` is the `dir` argument and where there is not. What is the motivation for that? Do we really need this?

Furthermore, both cases have a bug that I illustrate below using the following file:
```
file.create("model03012018")
```

**Bug 1**:

In case the `dir` argument does not contain any `/`, the folder that is created is added a numerical index (`"_\\d"`), even when the proposed directory does not already exist:
```
make_wkdir("dir03012018", "model03012018")
```
This is not a fatal bug but it doesn't make much sense: it should add a numerical index only when the proposed directory name already exists.

**Bug 2**:

When there is a `/ ` is the `dir` argument, and when the proposed name does not already exist, the function `make_wkdir()` behaves as expected in the sense that it doesn't add a numerical index to the proposed name:
```
unlink("dir03012018_1", TRUE)
make_wkdir(paste0(getwd(), "/dir03012018"), "model03012018")
```
However, the bug in that case is that it does not do the check whether the proposed `dir` already exists or not
```
make_wkdir(paste0(getwd(), "/dir03012018"), "model03012018")
```
whereas it should as was done above in the case where there is no `/` in `dir`.

Don't forget to clean!:
```
unlink("dir03012018", TRUE)
file.remove("model03012018")
```

**Comment by meta00** [comment]
make_wkdir discriminate the two cases: with "/" and without "/" because the former allows to create simulation result directory with the path indicated and the latter in the current working directory (default behaviour).

**Comment by choisy** [comment]
Not sure I understand. Can you explain in more detail please?

**Comment by LucieContamin** [comment]
As I understand it, the function was created to be able to: 
- create a directory of we  input a directory name without "/", like for example, make_wkdir("test", "model_test") will automatically create a directory in the current directory.
But if your input make_wkdir("path/to/test", "model_test"), it will create a directory into path/to.
So I don't really understand the use of this if.

With the new version it's still able to do that, so we are good!

**Comment by choisy** [comment]
Ah yes, sure!
Thanks both!
