### ISSUE TITLE
Bug while installing package

### ISSUE THREAD

**Issue by jdzucker** [r-and-gama/rama#69]
I might have done something wrong but I did a git pull and then after doing a
build and install I get the following message that may be caused by using an unknown isWindows() function :

==> devtools::document(roclets=c('rd', 'collate', 'namespace', 'vignette'))

Updating rama documentation
Loading rama
Using default directory name "sir" in current directory "/Users/jdz/Library/Mobile Documents/com~apple~CloudDocs/DOCS-CLEFS/Programmation/R/R-FONCTIONS/RAMA-GAMAR/rama".Simulations results will be saved in "/Users/jdz/Library/Mobile Documents/com~apple~CloudDocs/DOCS-CLEFS/Programmation/R/R-FONCTIONS/RAMA-GAMAR/rama/sir_1".

Running experiment plan ...Error in isWindows() (from call_gama.R#34) : could not find function "isWindows"
Calls: suppressPackageStartupMessages ... eval -> eval -> system.time -> run_experiment -> call_gama
Timing stopped at: 0.047 0.002 0.05
Execution halted

Exited with status 1.

**Comment by LucieContamin** [comment]
I can not manage to reproduce your example.  
The function `isWindows` is normally in the file rama/R/utils.R at the line 6: 
```r
# Test if operating system is Windows ------------------------------------------
isWindows <- function() {
  return (Sys.info()["sysname"] == "Windows")
}
```
Can you check if it is available in your local version ?

Also, I realize that we got two versions of two functions: `get_os` and `gama_remote_distrib` in `rama/R/zzz.R` and `rama/R/utils.R`, with an old version of the functions in the `utils.R` file. I remove the `utils.R` version.

After cleaning my environment and also deleting potential logs of previous build attempts, I manage to build and install the package without any troubles.

**Comment by choisy** [comment]
Jean-Daniel, did you clean your environment and your previous build attempts logs before rebuilding locally?

**Comment by LucieContamin** [comment]
@choisy we can copy-paste the function `gama_remote_distrib` and the function `get_os` to `utils.R` without any problem. I will do it.

**Comment by jdzucker** [comment]
I had cleaned my environment. 
Furthemore when I do 
> library(rama)
> isWindows()
Error in isWindows() : could not find function "isWindows"
But I see it in utils.R
After executing utils.R 
> isWindows()
sysname 
  FALSE 
>

**Comment by LucieContamin** [comment]
The behavior of `isWindows` is good in your last message: 
The function is not exported, the user should not be able to use it directly. 
```
library(rama)
isWindows()
# Error in isWindows() : could not find function "isWindows"
```
But when you load it, it should return FALSE when used on a mac:
```r
isWindows()
# sysname
# FALSE
```
That a good news, the function `isWindows` seems to be working correctly on your computer. 
Maybe, it's a problem a old logs still in your build path, did you erase any old logs ?

**Comment by jdzucker** [comment]
How do I do that ? Thanks for your help

**Comment by LucieContamin** [comment]
The previous logs (if they exist) should be in the same folder as the one containing the rama package folder. For example, if `rama` is on the `Desktop` in a folder `package` (path: `Desktop/package/rama`), the logs should be into the `Desktop/package` folder . 

Currently, everytime we run a `CHECK` in Rstudio, a log with a warning is created and should be erased before re-running a `CHECK`. We are working on this issue. 

You're welcome for the help =)

**Comment by choisy** [comment]
Hi Jean-Daniel,
Does it work now? Otherwise, have you checked that you're on the master branch?
Please let us know.
Thanks, Marc.

**Comment by jdzucker** [comment]
After resetting my git (as I had advanced commit) I managed to be now uptodate and rebuild without pb.
