### ISSUE TITLE
Outdated example files

### ISSUE THREAD

**Issue by LucieContamin** [r-and-gama/rama#70]
In the folder `inst/examples`, there are three files named: `NicolasPred.R`, `predator_prey.R` and `sir.R`. These files are outdated, written to play in R (`gama`) with the three models with the same name. We should either delete them or rewrite them to correspond to the new interface of `rama`.

**Comment by choisy** [comment]
Ah yes, of course. Ideally would be to rewrite them.

**Comment by choisy** [comment]
Addressed by pull request #81
