### ISSUE TITLE
`run_experiment` output empty folder and file

### ISSUE THREAD

**Issue by LucieContamin** [r-and-gama/rama#78]
The function `run_experiment()` creates, in some case, an empty `.txt` file and and empty folder. For example :

```
#load experiment
gaml_file <- system.file("examples", "sir.gaml", package = "rama")
exp1 <- load_experiment("sir", gaml_file, "sir")
# run experiment
out <- run_experiment(exp1)
```
 creates: 
```
console-outputs-1.txt (0 B)
simulation-outputs1.xml (161.1 KB)
snapchot (empty folder)
```
I understand that sometimes the folder `snapchot` and the file `console-outputs` can contains information. But, when they are empty, like in this example, can we autpmatically remove them or do you think it's better to keep them ?

**Comment by LucieContamin** [comment]
I was thinking like you that we can check and remove the file and folder if they are empty. But, I don't know if it's necessary to print a message. The user already received a lot of messages. What do you think?

**Comment by meta00** [comment]
We can remove the empty files without warning. 

But what is it in `console-output`? If the user needs to see it, we can provide a function to read this or show console-output contains errors/warnings, no?

**Comment by LucieContamin** [comment]
Done in pull-request #80
