### ISSUE TITLE
output of load_experiment loses attributes

### ISSUE THREAD

**Issue by LucieContamin** [r-and-gama/rama#8]
If we run this:
```r
out <- load_experiment("sir", "inst/examples/sir.gaml")
simulation_num  <- 10
my_experiment <- as.data.frame(lapply(out, rep, simulation_num))
```
my_experiment loses `model` and class `experiment` attributes

**Comment by choisy** [comment]
That's not the way to do. You should do
```
do.call(rbind, lapply(1:10, function(x) out))
```
instead. I'm happy to wrap this up into a code. What do you think?

**Comment by choisy** [comment]
As for `init_experiment`, can you please provide an concrete example?

**Comment by LucieContamin** [comment]
The function you propose is good for replication.  I think I was not clear with our problem, sorry for that.
The problem is if we want to change the data frame again without using "attributes friendly" function. 
For example, if we want to modify the column `p_I0` with `dplyr:: mutate`:  
```r
out2 <- repl(out, 10)
df <- dplyr::mutate(out2, p_I0 = c(1:10))
```
We are losing the attributes again: 

```r
str(df)
```
So, we propose the function `init_experiment` to recode the data frame with the "good" structure with the two attributes `class` containing `experiment` and `model`. 

```r
df <- init_experiment(df, model(out))
str(df)
```

**Comment by meta00** [comment]
Done
