### ISSUE TITLE
Question in show_experiment()

### ISSUE THREAD

**Issue by choisy** [r-and-gama/rama#83]
Line 45 of [show_experiment.R](https://github.com/r-and-gama/rama/blob/master/R/show_experiment.R), what is the use of `lapply(exp_info, function(x) x)`?
Given that `exp_info` is a list, `identical(exp_info, lapply(exp_info, function(x) x))` is `TRUE`.
Should we then replace this by simply `exp_info`?

**Comment by LucieContamin** [comment]
Yes, we can replace `lapply(exp_info, function(x) x)` for `exp_info`, I don't think it will cause any problem.

**Comment by choisy** [comment]
Done it commit 6125d0054807e9a18a92e6198a7cc8ac6aa8ac38.
