### ISSUE TITLE
Question in show_experiment()

### ISSUE THREAD

**Issue by choisy** [r-and-gama/rama#84]
In [show_experiment.R](https://github.com/r-and-gama/rama/blob/master/R/show_experiment.R), line 32, we declare a type GUI to the experiments that do not have any type. Is it OK? Meaning, is it a rule in GAMA that experiments without a type are by default of type GUI?

**Comment by meta00** [comment]
Yes, default type is GUI.

**Comment by choisy** [comment]
Lovely! Thanks!
