### ISSUE TITLE
Examples with display does not run

### ISSUE THREAD

**Issue by LucieContamin** [r-and-gama/rama#97]
The models' examples `snoubies.gaml` and `NicolasPred.gaml` (the only one with display) do not work currently. When inputted in the function `run_experiment`, the function does not return any error, warning or message and does not stop.  It seems that the `gama headless` has trouble and does not stop either. 
Maybe something is missing in the `gaml` (path ?) or in the folder containing the models (includes ?)

**Comment by meta00** [comment]
resolved in the latest Gama, we can use other models as examples.
