### ISSUE TITLE
Website/reference

### ISSUE THREAD

**Issue by choisy** [r-and-gama/rama#98]
`get_parameters_names()`,  `get_variables_names()`and `get_all_names()` should be moved from "manipulating experiment objects" to "Reading GAML files".

**Comment by choisy** [comment]
Actually, they should simply be suppressed from "manipulating experiment objects" since they already are in "Reading GAML files".

**Comment by LucieContamin** [comment]
Adress in pull-request: Adress multiple issues #115
Functions were removed
